version: '3'
services:
  mongo:
    image: mongo:6.0.3
    hostname: mongo
    volumes:
      - ./mongo:/db/data:rw
      - ./mongo/mongo.conf:/etc/mongo/mongo.conf:ro
    env_file:
      - ./mongo/.env
    command:
      - --config
      - /etc/mongo/mongo.conf
    ports:
      - 27017:27017
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-c',
          'echo ''db.runCommand("ping").ok'' | mongosh localhost:27017 --quiet',
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - mongo

networks:
  mongo:
    name: mongo
